<?php
/**
 * /home/pacho/yiiApps/gianFISAO/runtime/giiant/358b0e44f1c1670b558e36588c267e47
 *
 * @package default
 */


// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\controllers\base;

use app\modules\crud\models\InicioCarousel;
use app\modules\crud\models\search\InicioCarousel as InicioCarouselSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
 * InicioCarouselController implements the CRUD actions for InicioCarousel model.
 */
class InicioCarouselController extends Controller
{


	/**
	 *
	 * @var boolean whether to enable CSRF validation for the actions in this controller.
	 * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
	 */
	public $enableCsrfValidation = false;


	/**
	 * Lists all InicioCarousel models.
	 *
	 * @return mixed
	 */
	public function actionIndex() {
		$searchModel  = new InicioCarouselSearch;
		$dataProvider = $searchModel->search($_GET);

		Tabs::clearLocalStorage();

		Url::remember();
		\Yii::$app->session['__crudReturnUrl'] = null;

		return $this->render('index', [
				'dataProvider' => $dataProvider,
				'searchModel' => $searchModel,
			]);
	}


	/**
	 * Displays a single InicioCarousel model.
	 *
	 * @param integer $id_carousel
	 * @return mixed
	 */
	public function actionView($id_carousel) {
		\Yii::$app->session['__crudReturnUrl'] = Url::previous();
		Url::remember();
		Tabs::rememberActiveState();

		return $this->render('view', [
				'model' => $this->findModel($id_carousel),
			]);
	}


	/**
	 * Creates a new InicioCarousel model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new InicioCarousel;

		try {
			if ($model->load($_POST) && $model->save()) {
				return $this->redirect(['view', 'id_carousel' => $model->id_carousel]);
			} elseif (!\Yii::$app->request->isPost) {
				$model->load($_GET);
			}
		} catch (\Exception $e) {
			$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
			$model->addError('_exception', $msg);
		}
		return $this->render('create', ['model' => $model]);
	}


	/**
	 * Updates an existing InicioCarousel model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id_carousel
	 * @return mixed
	 */
	public function actionUpdate($id_carousel) {
		$model = $this->findModel($id_carousel);

		if ($model->load($_POST) && $model->save()) {
			return $this->redirect(Url::previous());
		} else {
			return $this->render('update', [
					'model' => $model,
				]);
		}
	}


	/**
	 * Deletes an existing InicioCarousel model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id_carousel
	 * @return mixed
	 */
	public function actionDelete($id_carousel) {
		try {
			$this->findModel($id_carousel)->delete();
		} catch (\Exception $e) {
			$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
			\Yii::$app->getSession()->addFlash('error', $msg);
			return $this->redirect(Url::previous());
		}


		// TODO: improve detection
		$isPivot = strstr('$id_carousel', ',');
		if ($isPivot == true) {
			return $this->redirect(Url::previous());
		} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
			Url::remember(null);
			$url = \Yii::$app->session['__crudReturnUrl'];
			\Yii::$app->session['__crudReturnUrl'] = null;

			return $this->redirect($url);
		} else {
			return $this->redirect(['index']);
		}
	}


	/**
	 * Finds the InicioCarousel model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @throws HttpException if the model cannot be found
	 * @param integer $id_carousel
	 * @return InicioCarousel the loaded model
	 */
	protected function findModel($id_carousel) {
		if (($model = InicioCarousel::findOne($id_carousel)) !== null) {
			return $model;
		} else {
			throw new HttpException(404, 'The requested page does not exist.');
		}
	}


}
