<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "Club".
 *
 * @property integer $id_club
 * @property string $nombre_club
 * @property string $direccion
 *
 * @property \app\modules\crud\models\Equipo[] $equipos
 * @property string $aliasModel
 */
abstract class Club extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Club';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre_club'], 'string', 'max' => 120],
            [['direccion'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_club' => Yii::t('models', 'Id Club'),
            'nombre_club' => Yii::t('models', 'Nombre Club'),
            'direccion' => Yii::t('models', 'Direccion'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEquipos()
    {
        return $this->hasMany(\app\modules\crud\models\Equipo::className(), ['club_id' => 'id_club']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\ClubQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ClubQuery(get_called_class());
    }


}
