<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "fecha".
 *
 * @property integer $id_fecha
 * @property integer $torneo_id
 * @property integer $numero
 * @property string $estado
 *
 * @property \app\modules\crud\models\Torneo $torneo
 * @property string $aliasModel
 */
abstract class Fecha extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'fecha';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['torneo_id', 'numero'], 'integer'],
            [['estado'], 'string', 'max' => 45],
            [['torneo_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\Torneo::className(), 'targetAttribute' => ['torneo_id' => 'id_torneo']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_fecha' => Yii::t('models', 'Id Fecha'),
            'torneo_id' => Yii::t('models', 'Torneo ID'),
            'numero' => Yii::t('models', 'Numero'),
            'estado' => Yii::t('models', 'Estado'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTorneo()
    {
        return $this->hasOne(\app\modules\crud\models\Torneo::className(), ['id_torneo' => 'torneo_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\FechaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\FechaQuery(get_called_class());
    }


}
