<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "inicioCarousel".
 *
 * @property integer $id_carousel
 * @property string $titulo_carousel
 * @property string $texto_carousel
 * @property string $image_path
 * @property string $boton_carousel
 * @property string $aliasModel
 */
abstract class InicioCarousel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inicioCarousel';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['titulo_carousel', 'texto_carousel', 'image_path', 'boton_carousel'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_carousel' => Yii::t('models', 'Id Carousel'),
            'titulo_carousel' => Yii::t('models', 'Titulo Carousel'),
            'texto_carousel' => Yii::t('models', 'Texto Carousel'),
            'image_path' => Yii::t('models', 'Image Path'),
            'boton_carousel' => Yii::t('models', 'Boton Carousel'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\InicioCarouselQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\InicioCarouselQuery(get_called_class());
    }


}
