<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "jugador".
 *
 * @property integer $id_jugador
 * @property integer $equipo_id
 * @property string $nombre_jugador
 * @property integer $categoria
 * @property string $apellido_jugador
 *
 * @property \app\modules\crud\models\Gole[] $goles
 * @property \app\modules\crud\models\Equipo $equipo
 * @property string $aliasModel
 */
abstract class Jugador extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jugador';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['equipo_id', 'categoria'], 'integer'],
            [['nombre_jugador', 'apellido_jugador'], 'string', 'max' => 120],
            [['equipo_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\Equipo::className(), 'targetAttribute' => ['equipo_id' => 'id_equipo']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_jugador' => Yii::t('models', 'Id Jugador'),
            'equipo_id' => Yii::t('models', 'Equipo ID'),
            'nombre_jugador' => Yii::t('models', 'Nombre Jugador'),
            'categoria' => Yii::t('models', 'Categoria'),
            'apellido_jugador' => Yii::t('models', 'Apellido Jugador'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGoles()
    {
        return $this->hasMany(\app\modules\crud\models\Gole::className(), ['jugador_id' => 'id_jugador']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEquipo()
    {
        return $this->hasOne(\app\modules\crud\models\Equipo::className(), ['id_equipo' => 'equipo_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\JugadorQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\JugadorQuery(get_called_class());
    }


}
