<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "liga".
 *
 * @property integer $id_liga
 * @property integer $torneo_id
 * @property integer $categoria
 *
 * @property \app\modules\crud\models\Torneo $torneo
 * @property string $aliasModel
 */
abstract class Liga extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'liga';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['torneo_id', 'categoria'], 'integer'],
            [['torneo_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\Torneo::className(), 'targetAttribute' => ['torneo_id' => 'id_torneo']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_liga' => Yii::t('models', 'Id Liga'),
            'torneo_id' => Yii::t('models', 'Torneo ID'),
            'categoria' => Yii::t('models', 'Categoria'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTorneo()
    {
        return $this->hasOne(\app\modules\crud\models\Torneo::className(), ['id_torneo' => 'torneo_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\LigaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\LigaQuery(get_called_class());
    }


}
