<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "profile".
 *
 * @property integer $user_id
 * @property string $name
 * @property string $public_email
 * @property string $gravatar_email
 * @property string $gravatar_id
 * @property string $location
 * @property string $website
 * @property string $bio
 * @property string $timezone
 *
 * @property \app\modules\crud\models\User $user
 * @property string $aliasModel
 */
abstract class Profile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'profile';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bio'], 'string'],
            [['name', 'public_email', 'gravatar_email', 'location', 'website'], 'string', 'max' => 255],
            [['gravatar_id'], 'string', 'max' => 32],
            [['timezone'], 'string', 'max' => 40],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('models', 'User ID'),
            'name' => Yii::t('models', 'Name'),
            'public_email' => Yii::t('models', 'Public Email'),
            'gravatar_email' => Yii::t('models', 'Gravatar Email'),
            'gravatar_id' => Yii::t('models', 'Gravatar ID'),
            'location' => Yii::t('models', 'Location'),
            'website' => Yii::t('models', 'Website'),
            'bio' => Yii::t('models', 'Bio'),
            'timezone' => Yii::t('models', 'Timezone'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\modules\crud\models\User::className(), ['id' => 'user_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\ProfileQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ProfileQuery(get_called_class());
    }


}
