<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "torneo".
 *
 * @property integer $id_torneo
 * @property string $nombre_torneo
 * @property string $fecha_inicio
 * @property string $fecha_fin
 *
 * @property \app\modules\crud\models\Fecha[] $fechas
 * @property \app\modules\crud\models\Liga[] $ligas
 * @property \app\modules\crud\models\Partido[] $partidos
 * @property string $aliasModel
 */
abstract class Torneo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'torneo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha_inicio', 'fecha_fin'], 'safe'],
            [['nombre_torneo'], 'string', 'max' => 120]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_torneo' => Yii::t('models', 'Id Torneo'),
            'nombre_torneo' => Yii::t('models', 'Nombre Torneo'),
            'fecha_inicio' => Yii::t('models', 'Fecha Inicio'),
            'fecha_fin' => Yii::t('models', 'Fecha Fin'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFechas()
    {
        return $this->hasMany(\app\modules\crud\models\Fecha::className(), ['torneo_id' => 'id_torneo']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLigas()
    {
        return $this->hasMany(\app\modules\crud\models\Liga::className(), ['torneo_id' => 'id_torneo']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPartidos()
    {
        return $this->hasMany(\app\modules\crud\models\Partido::className(), ['torneo_id' => 'id_torneo']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\TorneoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\TorneoQuery(get_called_class());
    }


}
